################################################################################
# Name: Nega Demeke
# User Name: demeken
# Repo link: https://github.com/Berea-College-CSC-226/a03-master-sp23.git
# Google Doc: https://docs.google.com/document/d/1KCoJ7mJg88NT3KncYAzkNQNcPg1QiJMmfDkzrCGoI9I/edit?usp=sharing
########################################################################################

import turtle
def house():     #I create a function called house
    partt= turtle.Turtle() #name the function turtle partt
    partt.penup()
    partt.pensize(3)
    partt.color("black","bisque1")
    partt.begin_fill()

    partt.goto(-200,-150)
    partt.pendown()
    partt.forward(400)
    partt.left(90)
    partt.forward(200)
    partt.left(90)
    partt.forward(400)
    partt.left(90)
    partt.forward(200)
    partt.left(90)
    partt.end_fill()

#create partiton
    partt.forward(100)
    partt.left(90)
    partt.forward(200)
    partt.left(90)
    partt.forward(100)
    partt.end_fill()
    partt.penup()
#create roof
    partt.color("black","DarkSlateGrey")
    partt.begin_fill()
    partt.right(120)
    partt.forward(100)
    partt.right(120)
    partt.forward(100)
    partt.end_fill()
    partt.begin_fill()
    partt.backward(100)
    partt.left(60)
    partt.forward(300)
    partt.right(60)
    partt.forward(100)
    partt.end_fill()
# create door

    partt = turtle.Turtle()
    partt.penup()
    partt.goto(-200,-150)
    partt.setheading(0)
    partt.pendown()
    partt.color("black","DarkOrchid4")
    partt.forward(230)
    partt.left(90)
    partt.begin_fill()
    partt.forward(90)
    partt.right(90)
    partt.forward(50)
    partt.right(90)
    partt.forward(90)
    partt.end_fill()
    partt.penup()
    #create left window1
    partt.goto(-60,-50)
    partt.pendown()
    partt.color("black","DarkOrchid4")
    partt.begin_fill()
    partt.backward(50)
    partt.left(90)
    partt.forward(60)
    partt.right(90)
    partt.forward(50)
    partt.right(90)
    partt.forward(60)
    partt.right(90)
    partt.forward(25)
    partt.right(90)
    partt.forward(60)
    partt.backward(30)
    partt.right(90)
    partt.forward(25)
    partt.backward(50)
    partt.end_fill()
    #creqte right window
    partt.penup()
    partt.setheading(270)
    partt.goto(100,-50)
    partt.pendown()
    partt.color("black","DarkOrchid4")
    partt.begin_fill()
    partt.backward(50)
    partt.left(90)
    partt.forward(60)
    partt.right(90)
    partt.forward(50)
    partt.right(90)
    partt.forward(60)
    partt.right(90)
    partt.forward(25)
    partt.right(90)
    partt.forward(60)
    partt.backward(30)
    partt.right(90)
    partt.forward(25)
    partt.backward(50)
    partt.end_fill()
    partt.penup()
    #green area
    partt.color("black","chartreuse2")
    partt.goto(-650,-150)
    partt.left(90)
    partt.pendown()
    partt.begin_fill()
    partt.forward(1300)
    partt.right(90)
    partt.forward(180)
    partt.right(90)
    partt.forward(1300)
    partt.right(90)
    partt.forward(180)
    partt.end_fill()
    partt.penup()

def sunrays():
    sunrayss = turtle.Turtle()
    sunrayss.penup()
    #create circle of sun
    sunrayss.goto(-500,100)
    sunrayss.pendown()
    sunrayss.color("black","yellow")
    sunrayss.begin_fill()
    sunrayss.circle(45)
    sunrayss.end_fill()
    sunrayss.goto(-545,150)
    #create sunrays
    sunrayss.pensize(5)
    for i in range(12):
            sunrayss.forward(80)
            sunrayss.backward(80)
            sunrayss.left(30)
    sunrayss.penup()
#create clouds
def clouds(): # I am creating a cloud and put it a function called clouds
    cloudss = turtle.Turtle()
    cloudss.penup()
    cloudss.goto(500,160)
    cloudss.pendown()
    cloudss.color("yellow","yellow")
    cloudss.setheading(90)
    cloudss.begin_fill()
    cloudss.circle(60,180)
    cloudss.end_fill()
    cloudss.goto(440,160)
    cloudss.setheading(90)
    cloudss.begin_fill()
    cloudss.circle(80,180)
    cloudss.end_fill()

def main():

    negad = turtle.getscreen() # name the turtle screen as negad
    negad.bgcolor("aquamarine2") # make the screen background aquamarine2
    house() # call the function called house()
    sunrays() #call the function called sunrays()
    clouds() #call the function called clouds()
    negad.exitonclick()
main()

