################################################################################
# Name: Alberto Doroteo-Reyes
# Username: Doroteoreyesa
# Repo link: https://github.com/Berea-College-CSC-226/a03-master-sp23.git
# Google Doc link: https://docs.google.com/document/d/14_Ky2XNH-HKEWnjSQkfXKKazAwmIa70oO4fgdGXr1yA/edit#
########################################################################################

import turtle

def eyes():
    beto = turtle.Turtle()
    beto.penup()
    beto.goto(-100, 100)
    beto.pendown()
    beto.pensize(1)
    beto.speed(1000)
    beto.fillcolor("white")
    beto.begin_fill()
    beto.pencolor("black")
    for i in range(2):
        beto.forward(30)
        beto.right(45)
        beto.forward(5)
        beto.right(45)
        beto.forward(5)
        beto.right(45)
        beto.forward(5)
        beto.right(45)
        beto.forward(30)
    beto.right(90)
    beto.end_fill()
    beto.fillcolor("black")
    beto.begin_fill()
    for i in range(2):
        beto.forward(10)
        beto.left(90)
        beto.forward(10)
        beto.left(90)
    beto.end_fill()
    beto.penup()
    beto.goto(100, 100)
    beto.right(270)
    beto.pendown()
    beto.fillcolor("white")
    beto.begin_fill()
    beto.pencolor("black")
    for i in range(2):
        beto.forward(30)
        beto.right(45)
        beto.forward(5)
        beto.right(45)
        beto.forward(5)
        beto.right(45)
        beto.forward(5)
        beto.right(45)
        beto.forward(30)
    beto.right(90)
    beto.end_fill()
    beto.fillcolor("black")
    beto.begin_fill()
    for i in range(2):
        beto.forward(10)
        beto.left(90)
        beto.forward(10)
        beto.left(90)
    beto.end_fill()
    beto.hideturtle()
def face():
    beto = turtle.Turtle()
    beto.speed(1000)
    beto.penup()
    beto.goto(-200, 200)
    beto.pendown()
    beto.fillcolor("#C4A484")
    beto.begin_fill()
    beto.right(90)
    beto.fd(250)
    beto.left(45)
    beto.forward(150)
    beto.left(45)
    beto.forward(180)
    beto.left(45)
    beto.forward(150)
    beto.left(45)
    beto.forward(250)
    beto.left(90)
    beto.forward(393)
    beto.end_fill()
    beto.hideturtle()

def lessmile():
    beto = turtle.Turtle()
    beto.speed(1000)
    beto.fillcolor("red")
    beto.begin_fill()
    beto.forward(50)
    beto.left(45)
    beto.fd(15)
    beto.right(45)
    beto.forward(15)
    beto.right(135)
    beto.left(45)
    beto.forward(10)
    beto.right(45)
    beto.forward(25)
    beto.right(45)
    beto.forward(60)
    beto.fd(50)
    beto.end_fill()
    beto.penup()
    beto.goto(0, 0)
    beto.pendown()
    beto.begin_fill()
    beto.forward(50)
    beto.right(45)
    beto.fd(15)
    beto.left(45)
    beto.forward(15)
    beto.left(135)
    beto.right(45)
    beto.forward(10)
    beto.left(45)
    beto.forward(25)
    beto.left(45)
    beto.forward(60)
    beto.end_fill()
    beto.penup()
    beto.goto(0, -10)
    beto.pendown()
    beto.forward(50)
    beto.left(45)
    beto.forward(15)
    beto.forward(-15)
    beto.right(45)
    beto.forward(-100)
    beto.right(45)
    beto.fd(-15)
    beto.fd(15)
    beto.hideturtle()


def hair():
    pelo = turtle.Turtle()
    pelo.speed(10)
    pelo.penup()
    pelo.goto(-185, 200)
    pelo.pendown()
    for i in range(14):
        for i in range(2):
            pelo.begin_fill()
            pelo.forward(20)
            pelo.left(135)
            pelo.fd(20)
            pelo.left(90)
            pelo.end_fill()
        pelo.right(90)
        pelo.forward(15)
def main():
    wn = turtle.Screen()
    turtle.bgcolor("#808080")
    face()
    eyes()
    lessmile()
    hair()
    wn.exitonclick()

main()

